### PR TITLE
Tornjak ingress doc.suggestions

### PR DESCRIPTION
**Pull request by kfox1111**

### CODE REVIEW

**Comment by mrsabath** [comment]
@kfox1111 when I do as you suggested on my Openshift cluster with the external ingress, I get the following:

```
helm-charts-hardened$kubectl -n spire-server get routes
NAME                           HOST/PORT                           PATH   SERVICES                 PORT                     TERMINATION     WILDCARD
spire-tornjak-6tsgw            tornjak-backend.production.other    /      spire-tornjak-backend    tornjak-srv-http         edge/Redirect   None
spire-tornjak-frontend-fsx86   tornjak-frontend.production.other   /      spire-tornjak-frontend   spire-tornjak-frontend   edge/Redirect   None
helm-charts-hardened$kubectl -n spire-server get ingress
NAME                                   CLASS    HOSTS                               ADDRESS                                                                                              PORTS     AGE
spire-server                           <none>   spire-server.production.other                                                                                                            80, 443   5m47s
spire-spiffe-oidc-discovery-provider   <none>   oidc-discovery.production.other                                                                                                          80, 443   5m47s
spire-tornjak                          <none>   tornjak-backend.production.other    router-default.mc-ztna-04-9d995c4a8c7c5f281ce13d5467ff6a94-0000.us-east.containers.appdomain.cloud   80        5m47s
spire-tornjak-frontend                 <none>   tornjak-frontend.production.other   router-default.mc-ztna-04-9d995c4a8c7c5f281ce13d5467ff6a94-0000.us-east.containers.appdomain.cloud   80        5m47s
```
I think we have to explicitly define what are the values for each ingress.

**Comment by kfox1111** [comment]
> @kfox1111 when I do as you suggested on my Openshift cluster with the external ingress, I get the following:
> 
> ```
> helm-charts-hardened$kubectl -n spire-server get routes
> NAME                           HOST/PORT                           PATH   SERVICES                 PORT                     TERMINATION     WILDCARD
> spire-tornjak-6tsgw            tornjak-backend.production.other    /      spire-tornjak-backend    tornjak-srv-http         edge/Redirect   None
> spire-tornjak-frontend-fsx86   tornjak-frontend.production.other   /      spire-tornjak-frontend   spire-tornjak-frontend   edge/Redirect   None
> helm-charts-hardened$kubectl -n spire-server get ingress
> NAME                                   CLASS    HOSTS                               ADDRESS                                                                                              PORTS     AGE
> spire-server                           <none>   spire-server.production.other                                                                                                            80, 443   5m47s
> spire-spiffe-oidc-discovery-provider   <none>   oidc-discovery.production.other                                                                                                          80, 443   5m47s
> spire-tornjak                          <none>   tornjak-backend.production.other    router-default.mc-ztna-04-9d995c4a8c7c5f281ce13d5467ff6a94-0000.us-east.containers.appdomain.cloud   80        5m47s
> spire-tornjak-frontend                 <none>   tornjak-frontend.production.other   router-default.mc-ztna-04-9d995c4a8c7c5f281ce13d5467ff6a94-0000.us-east.containers.appdomain.cloud   80        5m47s
> ```
> 
> I think we have to explicitly define what are the values for each ingress.

That looks like its trying to use production.other....

> @mrsabath I went through the openshift/readme, followed the instructions on Openshift Local, up to the point where I actually deployed the spire chart, then did:
> 
> ```
> helm upgrade --install --namespace spire-server spire charts/spire \
>   --values examples/production/values.yaml \
>   --values examples/openshift/openshift-values.yaml \
>   --values examples/tornjak/values.yaml \
>   --values examples/tornjak/values-ingress.yaml \
>   --values examples/production/example-your-values.yaml \
>   --render-subchart-notes
> ```
> 
> Then, opened https://tornjak-backend.apps-crc.testing/ and accepted the cert, then https://tornjak-frontend.apps-crc.testing/ works.

Need to follow the steps in https://github.com/spiffe/helm-charts-hardened/blob/main/examples/openshift/README.md

specifically the bits that say:
```
appdomain=$(oc get cm -n openshift-config-managed  console-public -o go-template="{{ .data.consoleURL }}" | sed 's@https://@@; s/^[^.]*\.//')
echo "$appdomain"
Update the example-your-values.yaml file with your subdomain. s/production.other/$appdomain from above/

**Comment by mrsabath** [comment]
OK, that works for me!

**Review by mrsabath — APPROVED** [review]
LGTM!

**Pull request merged**
